@startuml

class ToDoListApp {
    main()
    start()
}

class ToDoList {
    -name: String
    -tasks: ArrayList<Task>
    getName()
    setName()
}

class Task {
    -description: String
    -completed: boolean
    -dueDate: Date
    getDescription()
    setDescription()
    getDueDate()
    setDueDate()
    getCompleted()
    setCompleted()
}

class ToDoListController {
    -listName: label

    viewButtonClicked()
    renameButtonClicked()
    deleteButtonClicked()
    newListButtonClicked()
    saveListButtonClicked()
    saveAllListsButtonClicked()
    loadListButtonClicked()
    loadMultipleListsButtonClicked()
    loadMultipleLists()
    loadList()
    renameList()
    getLists()
    deleteList()
    saveList()
    createList()
}

class TaskListController{
    -itemTable: TableView
    allListsButtonClicked()
    allTasksButtonClicked()
    completedTasksButtonClicked()
    incompleteTasksButtonClicked()
    showToDoLists()
    showIncompleteTasks()
    showCompleteTasks()
    showAllTasks()
    ascendSort()
    descendSort()


}

javafx.Application <|-- ToDoListApp

ToDoListApp - ToDoListController

ToDoListController-ToDoList

ToDoList-Task


TaskListController -ToDoListApp
TaskListController-Task


@enduml